apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
specification:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: back21/backend:v1.0.0  
        ports:
        - containerPort: 5000
      volumeClaimTemplates:
      - metadata:
          name: backend-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi 
