version: "3.6"

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: client-container1
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/var/www/client"
    networks:
      - yolo_net
    depends_on:
      - backend
    image: back21/client:v1.1.0

  backend:
-23,6 +25,9 @@ services:
    command: "npm start"
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017/yolomy?retryWrites=true&writeConcern=majority&authSource=admin
      - DB_NAME=yolomy
    volumes:
      - "./backend:/var/www/backend"
    networks:
    32,16 +37,24 @@ services:
      yolo.db:
    image: mongo:latest
    container_name: yolo_db
   
environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password 
      MONGO_INITDB_DATABASE: local 
ports:
      - "27018:27017"
   
volumes:
      - mongo-data:/data/db
networks:
      - yolo_net
 
yolo_net:
    driver: bridge 
mongo-data:  
    driver: local  

