---
- name: Set up Vagrant VM with Docker and Web Application
  hosts: all
  become: yes    

  vars_files:
    - vars/main.yml

  roles:
    - backend-structures
    - frontend-structures
    - common-tasks

  tasks:
    - name: Clone the repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
      tags: app_setup
